# Generated by Django 5.0.6 on 2024-07-23 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Res", "0002_lane_report_reservation_payment_delete_booking_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rezerwacja",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("godzina", models.TimeField()),
                ("ilosc_osob", models.IntegerField()),
                ("imie", models.CharField(max_length=255)),
                ("telefon", models.CharField(max_length=20)),
                ("uwagi", models.TextField(blank=True)),
                ("nip", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Tor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numer", models.IntegerField()),
                ("bendy", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="lane",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="reservation",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.AddField(
            model_name="rezerwacja",
            name="tor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Res.tor"
            ),
        ),
        migrations.DeleteModel(
            name="Lane",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
    ]
