# Generated by Django 5.0.6 on 2024-07-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Res", "0003_rezerwacja_tor_remove_reservation_lane_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tor",
            old_name="bendy",
            new_name="bendy_dla_dzieci",
        ),
        migrations.RemoveField(
            model_name="rezerwacja",
            name="nip",
        ),
        migrations.AddField(
            model_name="rezerwacja",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="rezerwacja",
            name="imie",
            field=models.CharField(max_length=100),
        ),
    ]
