# Generated by Django 5.0.6 on 2024-07-23 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Res", "0005_lane_reservation_delete_rezerwacja_delete_tor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numer", models.IntegerField(unique=True)),
                ("ma_bandy", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="lane",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="user",
        ),
        migrations.CreateModel(
            name="Rezerwacja",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("godzina", models.TimeField()),
                ("liczba_osob", models.IntegerField()),
                ("imie", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=20)),
                ("uwagi", models.TextField(blank=True, null=True)),
                (
                    "tor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Res.tor"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Lane",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
    ]
