# Generated by Django 5.0.6 on 2024-07-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Res", "0006_tor_remove_reservation_lane_remove_reservation_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BowlingLane",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("has_child_bumpers", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("num_players", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("comments", models.TextField(blank=True)),
                (
                    "lane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Res.bowlinglane",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Rezerwacja",
        ),
        migrations.DeleteModel(
            name="Tor",
        ),
    ]
