# Generated by Django 5.0.6 on 2024-07-23 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Res", "0007_bowlinglane_reservation_delete_rezerwacja_delete_tor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BowlingAlley",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Lane",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "bowling_alley",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lanes",
                        to="Res.bowlingalley",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="reservation",
            name="lane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="Res.lane",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("lane", "start_time", "end_time")},
        ),
        migrations.DeleteModel(
            name="BowlingLane",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="num_players",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
    ]
