# Generated by Django 5.0.6 on 2024-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Res", "0008_bowlingalley_reservation_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="user_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
